### ISSUE TITLE
I'm getting an error.

### ISSUE THREAD

**Issue by maskelihileci** [FelixBer/FindFunc#1]
![image](https://user-images.githubusercontent.com/41159853/165875997-bb8683c2-7841-459f-afff-fe71ec59a9cf.png)

IDA PRO 7.6.210427
Python 3.8
Windows 10 x64

**Comment by maskelihileci** [comment]
I didn't put it in the plugin location, I started it with the script file feature.  The plugin worked fine.
But it has some problems

1.If you turn off Find Func, you cannot open it again. When you try to install the add-on again, it crashes.
2. alt+b IDA crashes when you search byte array

When you add a missing pattern to the naming, there is no naming feature to indicate what it is.

This is what I've discovered for now

**Comment by FelixBer** [comment]
Regarding the first crash, you need to open a file in IDA before running the script. I will add add a proper error message for this case.
I can also confirm points 1. and 2., and they only happen if you run the tool as scriptfile. Investigation pending...

> When you add a missing pattern to the naming, there is no naming feature to indicate what it is.

I dont understand what you mean by this.

Thanks for the report!

**Comment by FelixBer** [comment]
I have pushed a fix for all three problems. Please try the latest from repo, or the one attached.

[findfunc1.1.zip](https://github.com/FelixBer/FindFunc/files/8588818/findfunc1.1.zip)

**Comment by maskelihileci** [comment]
Since you explain why the first problem was caused I ran it after saving a project and it problem fixed

![image](https://user-images.githubusercontent.com/41159853/167061598-f2344cc3-b1dc-422a-b165-ff42097dbd10.png)

Tab 7 = I want to name this place.

Also feature to save and load multiple drop-down tables I request the feature.

**Comment by FelixBer** [comment]
Glad to hear it's working now. I'll add Tab-renaming to the feature request list.

What do you mean by "drop down tables"? Saving/loading multiple Tabs?

**Comment by maskelihileci** [comment]
The save load event saves and loads the selected ones. I would like to save and load the open project completely.

**Comment by FelixBer** [comment]
It's on my list.

**Comment by FelixBer** [comment]
I added renaming tabs (doubleclick them) and loading/saving session in the latest release.
