### ISSUE TITLE
Rule naming

### ISSUE THREAD

**Issue by shevernitskiy** [FelixBer/FindFunc#3]
Could you add option for naming rules? It will be super handy for my case.

I use bytepattern rules for finding offsets every time on new version of exe. So I have rule byte pattaern => function match. I switch on one rule and find one function. It will be convinient, if I could name rule with function name.

PS: Awesome plugin!:)

**Comment by FelixBer** [comment]
Thanks! My use case is similar, the idea is to have one tab per function (that way, i can have several patterns/rules for tricky matches as well as disabled patterns for backup) and one session (= collection of tabs) per binary version. You can then name the tabs by double clicking on them and save the session to file. Would this work for your purposes?

**Comment by shevernitskiy** [comment]
I'll try, thanks!:)

**Comment by shevernitskiy** [comment]
So, I tried to save one rule in each tab for one function.
I used multy row pattern. And then when i loaded my session, there was many rules for every single row in pattern (i created only one rule with many byte rows). And it's not work as expected.
This is rule in session file:
```
Tab string_copy_n
RuleBytePattern True False 48 89 5C 24 10 48 89 6C  24 18 56 57 41 57 48 83
EC 20 48 8B 69 18 49 8B  F0 4C 8B FA 48 8B D9 4C
3B C5 77 21 48 8B F9 48  83 FD 10 72 03 48 8B 39
48 89 71 10 48 8B CF E8  1D C6 03 01 C6 04 37 00
E9 A5 00 00 00 48 BF FF  FF FF FF FF FF FF 7F 48
3B F7 0F 87 AF 00 00 00  48 8B CE 4C 89 74 24 40
48 83 C9 0F 48 3B CF 77  1F 48 8B D5 48 8B C7 48
D1 EA 48 2B C2 48 3B E8  77 0E 48 8D 04 2A 48 8B
F9 48 3B C8 48 0F 42 F8  48 8D 4F 01 E8 2F 0A 00
00 4C 8B C6 48 89 73 10  49 8B D7 48 89 7B 18 48
8B C8 4C 8B F0 E8 A9 C5  03 01 41 C6 04 36 00 48
83 FD 10 72 2D 48 8B 0B  48 8D 55 01 48 81 FA 00
10 00 00 72 18 4C 8B 41  F8 48 83 C2 27 49 2B C8
48 8D 41 F8 48 83 F8 1F  77 26 49 8B C8 E8 6E AA
03 01 4C 89 33 4C 8B 74  24 40 48 8B 6C 24 50 48
8B C3 48 8B 5C 24 48 48  83 C4 20 41 5F 5F 5E C3
FF 15 AA 60 0A 01 CC E8  B4 65 FF FF CC CC CC CC
```
This is what I had on loading
<img width="875" alt="image" src="https://user-images.githubusercontent.com/28886342/211983947-806671bd-45da-4d9f-b6a2-f2f8221455ba.png">

UPD: i got it, just delete all \n
