### ISSUE TITLE
Is this still developed?

### ISSUE THREAD

**Issue by karpiyon** [FelixBer/FindFunc#4]
Thanks for sharing.
Is this being developed? 
Is there a new version?

**Comment by FelixBer** [comment]
in principle, yes. Bug reports, feature requests, prs are welcome. Are you missing anything?

**Comment by karpiyon** [comment]
Well, I was missing some for the things which are already on you TODO list, in this order:

1. OR combination of rules
2. Progress bar
3. Add rule xref in/out

The OR is could be very useful and if this can be implemented perhaps, IGNORE as well,
I was looking for 'add any 20h' and I got many results, most of them for 'add esp 20h'. Of course 'add esp 20h' was not what I was searching for and to be able to IGNORE it would be very helpful.

Thanks

**Comment by FelixBer** [comment]
Sorry for the late reply. 

> I was looking for 'add any 20h' and I got many results, most of them for 'add esp 20h'. Of course 'add esp 20h' was not what I was searching for and to be able to IGNORE it would be very helpful.

This should be possible with "inverted matches", no? Either for the asm or the opcode sequence.

I'll prioritize the TODOs you listed once I start working on the TODOs, but it's not actively planned from my side atm... PRs are always welcome though ;)
